### PR TITLE
INFINITY-3565 Fix build/instructions for collector-emitter example

### PR DESCRIPTION
**Pull request by nickbp**
Updates the build steps for building this example. Adds a step for users who want a native linux build.

### CODE REVIEW

**Comment by nickbp** [comment]
`goimports` wants a required import to be removed. any idea why?:

```
*** Running 'goimports' ... ***

./examples/collector-emitter/main.go
diff -u ./examples/collector-emitter/main.go.orig ./examples/collector-emitter/main.go
--- ./examples/collector-emitter/main.go.orig	2018-04-24 20:36:09.533897897 +0000
+++ ./examples/collector-emitter/main.go	2018-04-24 20:36:09.533897897 +0000
@@ -14,7 +14,6 @@
 
 	log "github.com/Sirupsen/logrus"
 
-	"github.com/dcos/dcos-metrics/examples/collector-emitter/metrics_schema"
 	"github.com/linkedin/goavro"
 )
```

**Comment by hectorj2f** [comment]
@nickbp I saw this behavior before. If you put an alias to the import, it'll work. To solve this problem, it might related to goimports version and or its activated flags.

**Comment by nickbp** [comment]
OK, should be all set now. Ended up tidying up some of the handling around schema generation in general

**Comment by nickbp** [comment]
ping

**Comment by philipnrmn** [comment]
Thanks for the PR.

**Pull request merged**
