### PR TITLE
Overhaul the docs

### PR DESCRIPTION
**Pull request by philipnrmn**
The docs were inconsistent and out of date (for example the [architecture doc](https://github.com/dcos/dcos-metrics/blob/master/docs/ARCHITECTURE.md), last updated before DC/OS 1.9 was released). This overhaul updates them to make them much more approachable, and to focus on answering questions like 'how do I use this software' rather than 'what data transport did you decide to use internally'.

Diffs are hard to read, so I'd suggest browsing from the README at https://github.com/dcos/dcos-metrics/tree/docs

- fixes [DCOS-21663](https://jira.mesosphere.com/browse/DCOS-21663) Overhaul docs for DC/OS Metrics

### CODE REVIEW

**Comment by bergerx** [comment]
It could also be helpful about briefly telling about the structure of the repo for those who want to contribute or developing an internal integration based on the provided endpoints.

E.g. the relationship between mesos-module, collectors, producers, plugins and how they communicate with each other.

Also, some links to these wiki pages could be really helpful:
* https://docs.mesosphere.com/1.11/api/agent-routes/#system
* https://docs.mesosphere.com/1.11/metrics/

**Comment by philipnrmn** [comment]
@bergerx thanks very much for reading through the docs! I'll add in some more developer-focused documentation shortly.

**Comment by ashahan** [comment]
@philipnrmn The Youtube link for the data Datadog video is pointing to the Prometheus video, just a friendly FYI
https://github.com/dcos/dcos-metrics/pull/141/files#diff-e1e108f1b6e5e485c47401c9a01781b6R50

**Comment by philipnrmn** [comment]
@ashahan whoops! thanks for the catch, that's fixed now.

**Pull request merged**
