### PR TITLE
Updated prometheus-dcos19.md vim->vi

### PR DESCRIPTION
**Pull request by edgarlanting**
Since `vim` isn't setup on Centos by default I'm proposing to change this in `vi`

### CODE REVIEW

**Comment by philipnrmn** [comment]
@edgarlanting sure thing (anything but `emacs`). Would you kindly make the same change in all the quickstart documents please?

**Comment by edgarlanting** [comment]
Sure thing @philipnrmn thanks for your comments on this!

**Comment by edgarlanting** [comment]
@philipnrmn Changed all currently available quickstart docs too (Librato & DataDog) to include this change with appropriate PRs

**Comment by philipnrmn** [comment]
I squashed all three of your PRs into one over at #161 - I'll close them out now. Thanks for the contribution!

**Pull request closed without merging**
