### PR TITLE
Correct method to build this using the go way

### PR DESCRIPTION
**Pull request by GabrielNicolasAvellaneda**
This is the way to build this project. It is fast and you don't need to do any manual work. If you try the old way that was described in this document you will have to do a lot of manual work to get all the dependencies.

### CODE REVIEW

**Comment by philipnrmn** [comment]
OK to test

**Comment by philipnrmn** [comment]
Hi @GabrielNicolasAvellaneda , thanks for taking the time to improve our documentation.

Next time, might I suggest you open one PR with three commits instead of three PRs with one commit apiece?

**Comment by GabrielNicolasAvellaneda** [comment]
Hi @philipnrmn yes, I agree on this. I just used the edit feature of github directly on your repo and wasn't sure how to do that, next time will be better :+1:

**Comment by philipnrmn** [comment]
Looks like our CI has had a hiccup and didn't run tests on this series of PRs, so I'm going to merge them manually. Thanks again @GabrielNicolasAvellaneda 🙂

**Pull request merged**
